apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80  # the port your application listens on
      targetPort: 3000  # the port your container exposes
  type: ClusterIP  # or NodePort, LoadBalancer as per your environment
